version: 2

models:
  - name: dim_products
    description: "Product measurement (product catalog)"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_customers
    description: "Customer measurement with aggregated purchase metrics"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_date
    description: "Calendar dimension for convenient analytics by time periods"
    columns:
      - name: date_day
        tests:
          - unique
          - not_null

  - name: fct_orders
    description: "Order fact table"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null